### ISSUE TITLE
temperature parameter

### ISSUE THREAD

**Issue by Not-IITian** [AlonLahav/MeshWalker#2]
Hi,

Thank you for putting the code online. when i run it on modelnet40 or cubes, i got this error:

File "train_val.py", line 255, in run_one_job
    train_val(params)
  File "train_val.py", line 168, in train_val
    gpu_tmpr = utils.get_gpu_temprature()
  File "/home/abhishek/Scr/MeshWalker/utils.py", line 42, in get_gpu_temprature
    temp = int(output)
ValueError: invalid literal for int() with base 10: ''

Thank you for your help

**Comment by AlonLahav** [comment]
Hi,
Thank you for this issue.
I will fix it this Tuesday.
Coud you please rais an issue at Github?

Alon.

בתאריך יום ב׳, 7 בדצמ׳ 2020, 17:45, מאת Abhishek Sharma ‏<
notifications@github.com>:

**Comment by Not-IITian** [comment]
Hi,
this notification was because I raised the issue on github :)

**Comment by AlonLahav** [comment]
The function `get_gpu_temprature` is used just to make sure that if the GPU temprature is too high (higher than 95 degree Celsius), the program will be aborted.
I can guess that you run yhis code in different operating system than I do.
Anyway, to wakaround this issue, I put it inside `try-except, since it is not so important.
